import {CONFIG} from '../src/config.js';import {load} from './data.js';
const $=x=>document.getElementById(x),S={page:'home',slide:0,season:null,comp:null,mode:'all',role:'all',search:'',data:{},error:''},esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=x=>String(x||'').toLowerCase().replace(/[^a-z0-9]/g,''),ours=x=>norm(x)===norm(S.data.team?.name||CONFIG.fallbackTeamName),done=f=>['finished','completed','finalized'].includes(f.status),date=d=>d?new Intl.DateTimeFormat('it-IT',{day:'2-digit',month:'short'}).format(new Date(d)):'—',time=d=>d?new Intl.DateTimeFormat('it-IT',{hour:'2-digit',minute:'2-digit'}).format(new Date(d)):'—',score=f=>f.home_score!=null&&f.away_score!=null?`${f.home_score} – ${f.away_score}`:'VS';
const tabs=[['home','Home','⌂'],['competitions','Competizioni','◫'],['calendar','Calendario','▦'],['roster','Rosa','♙'],['stats','Statistiche','⌁']];
const games=()=>S.data.fixtures?.filter(f=>ours(f.home_team)||ours(f.away_team)).sort((a,b)=>new Date(a.kickoff_at)-new Date(b.kickoff_at))||[],up=()=>games().filter(f=>!done(f)&&new Date(f.kickoff_at)>Date.now()-7200000),recent=()=>games().filter(done).reverse(),slides=()=>[...up().slice(0,2),...recent().slice(0,2)];
function crest(n){let o=S.data.opponents?.find(x=>norm(x.name)===norm(n)||norm(x.short_name)===norm(n)),src=ours(n)?S.data.team?.logo_url:o?.logo_url;return `<span class="crest">${src?`<img src="${esc(src)}" alt="">`:esc(String(n).slice(0,2).toUpperCase())}</span>`}
function duel(f){return `<div class="versus"><div class="team">${crest(f.home_team)}<strong>${esc(f.home_team)}</strong></div><div class="score">${esc(score(f))}<small>${done(f)?'FINALE':time(f.kickoff_at)}</small></div><div class="team">${crest(f.away_team)}<strong>${esc(f.away_team)}</strong></div></div>`}
function hero(){let a=slides();if(!a.length)return '<section class="hero"><div class="empty">Nessuna partita disponibile</div></section>';S.slide%=a.length;let f=a[S.slide];return `<section class="hero"><div class="hero-head"><span>${done(f)?'ULTIMO RISULTATO':'PROSSIMA PARTITA'}</span><span>${esc(date(f.kickoff_at))} · G${esc(f.round_no??'—')}</span></div><div class="hero-match">${duel(f)}</div><div class="hero-foot"><div class="dots">${a.map((_,i)=>`<button data-slide="${i}" class="${i===S.slide?'on':''}"></button>`).join('')}</div><button class="cta" data-fixture="${esc(f.id)}">Match center ↗</button></div></section>`}
function row(f){return `<div class="match-row" data-fixture="${esc(f.id)}"><div class="datebox"><strong>${esc(date(f.kickoff_at).split(' ')[0])}</strong><small>${esc(date(f.kickoff_at).split(' ')[1])}</small></div><div class="match-text"><strong>${esc(f.home_team)} – ${esc(f.away_team)}</strong><small>${esc(time(f.kickoff_at))} · G${esc(f.round_no??'—')}</small></div><span class="result">${esc(score(f))}</span></div>`}
const panel=(t,b)=>`<section class="panel glass"><h2>${esc(t)}</h2>${b}</section>`;
function standings(c){let a=(S.data.standings||[]).filter(x=>!c||x.competition_id===c).sort((a,b)=>b.points-a.points||b.goal_difference-a.goal_difference||b.goals_for-a.goals_for);return a.length?`<div class="table-scroll"><table><thead><tr><th>#</th><th>Squadra</th><th>G</th><th>V</th><th>N</th><th>P</th><th>DR</th><th>Pt</th></tr></thead><tbody>${a.map((x,i)=>`<tr class="${ours(x.team)?'mine':''}"><td>${i+1}</td><td><b>${esc(x.team)}</b></td><td>${esc(x.played)}</td><td>${esc(x.won??'—')}</td><td>${esc(x.drawn??'—')}</td><td>${esc(x.lost??'—')}</td><td>${esc(x.goal_difference)}</td><td><b>${esc(x.points)}</b></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Classifica non disponibile</div>'}
function kpis(){let a={played:0,w:0,d:0,l:0,gf:0,ga:0};recent().forEach(f=>{let gf=ours(f.home_team)?f.home_score:f.away_score,ga=ours(f.home_team)?f.away_score:f.home_score;if(gf==null||ga==null)return;a.played++;a.gf+=gf;a.ga+=ga;a[gf>ga?'w':gf<ga?'l':'d']++});return `<div class="stats">${[['played','Giocate'],['w','Vittorie'],['d','Pareggi'],['l','Sconfitte'],['gf','Gol fatti'],['ga','Gol subiti']].map(([k,l])=>`<div class="stat glass"><strong>${a[k]}</strong><small>${l}</small></div>`).join('')}</div>`}
const heading=(eye,t)=>`<div class="eyebrow">${eye}</div><h1 class="title">${t}</h1>`,filters=(a,k,v)=>`<div class="filters">${a.map(([id,t])=>`<button class="filter ${id===v?'on':''}" data-${k}="${esc(id)}">${esc(t)}</button>`).join('')}</div>`;
function home(){let feed=[...up().slice(0,2),...recent().slice(0,2)];return heading('MATCHDAY','La stagione, in un colpo d’occhio.')+`<div class="hero-grid">${hero()}<aside class="sidecard glass"><h2>Match feed</h2>${feed.map(f=>`<div class="mini" data-fixture="${f.id}"><small>${date(f.kickoff_at)}</small><div class="mini-line"><span>${esc(f.home_team)}</span><b>${score(f)}</b><span>${esc(f.away_team)}</span></div></div>`).join('')||'<div class="empty">Nessuna gara</div>'}</aside></div>`+kpis()+`<div class="content-grid">${panel('In arrivo',up().slice(0,5).map(row).join('')||'<div class="empty">Nessuna gara futura</div>')}${panel('Classifica',standings(S.data.competitions?.[0]?.id))}</div>`}
function competitions(){S.comp=S.comp||S.data.competitions?.[0]?.id;return heading('COMPETIZIONI','Classifica e calendario.')+filters((S.data.competitions||[]).map(c=>[c.id,c.name]),'comp',S.comp)+`<div class="content-grid">${panel('Classifica',standings(S.comp))}${panel('Partite',(S.data.fixtures||[]).filter(f=>f.competition_id===S.comp).sort((a,b)=>new Date(a.kickoff_at)-new Date(b.kickoff_at)).map(row).join(''))}</div>`}
function calendar(){let a=games().filter(f=>S.mode==='all'||(S.mode==='results'?done(f):!done(f)));return heading('CALENDARIO','Tutte le partite del Caselle.')+filters([['all','Tutte'],['future','Da giocare'],['results','Risultati']],'mode',S.mode)+panel('Programma',a.map(row).join('')||'<div class="empty">Nessuna partita</div>')}
function playerGrid(){return (S.data.roster||[]).filter(x=>x.active!==false).map(r=>({r,p:S.data.stats?.find(p=>p.player_id===r.player_id)})).filter(x=>x.p&&(S.role==='all'||String(x.p.position_group||'').toUpperCase().startsWith(S.role))&&(x.p.first_name+' '+x.p.last_name).toLowerCase().includes(S.search.toLowerCase())).map(({r,p})=>`<button class="player" data-player="${p.player_id}"><span class="avatar">${esc(p.first_name?.[0])}${esc(p.last_name?.[0])}</span><h3>${esc(p.first_name)} ${esc(p.last_name)}</h3><small>${esc(p.position_group||'Ruolo non noto')} · #${esc(r.shirt_number??'—')}</small><p>${esc(p.appearances??'—')} pres. · ${esc(p.goals??'—')} gol</p></button>`).join('')||'<div class="empty">Nessun giocatore</div>'}
function roster(){return heading('ROSA','Giocatori della stagione.')+filters([['all','Tutti'],['P','Portieri'],['D','Difensori'],['C','Centrocampisti'],['A','Attaccanti']],'role',S.role)+`<input id="search" class="pill" placeholder="Cerca giocatore…" value="${esc(S.search)}"><div class="players" id="players" style="margin-top:14px">${playerGrid()}</div>`}
function stats(){let a=(S.data.stats||[]).slice().sort((a,b)=>(b.goals||0)-(a.goals||0));return heading('STATISTICHE','Numeri registrati, non inventati.')+kpis()+`<div class="content-grid">${panel('Marcatori',a.map((p,i)=>`<div class="match-row"><b>${i+1}</b><div class="match-text"><strong>${esc(p.first_name)} ${esc(p.last_name)}</strong><small>${esc(p.appearances??'—')} presenze</small></div><b>${esc(p.goals??'—')} gol</b></div>`).join(''))}${panel('Ultimi risultati',recent().slice(0,8).map(row).join(''))}</div>`}
function render(){let nav=tabs.map(([id,t,i])=>`<button class="nav ${S.page===id?'active':''}" data-nav="${id}"><i>${i}</i><span>${t}</span></button>`).join(''),team=S.data.team||{};$('root').innerHTML=`<div class="shell"><aside class="side glass"><div class="brand"><div class="brandmark">TM</div><span>Team Manager</span></div>${nav}<div class="spacer"></div></aside><div class="page"><header class="top glass"><div class="identity">${team.logo_url?`<img src="${esc(team.logo_url)}" alt="">`:''}<div><strong>${esc(team.name||CONFIG.fallbackTeamName)}</strong><small>${esc(S.data.seasons?.find(x=>x.id===S.season)?.name||'')}</small></div></div><div class="tools"><select class="pill" id="season">${(S.data.seasons||[]).map(x=>`<option value="${x.id}" ${x.id===S.season?'selected':''}>${esc(x.name)}</option>`).join('')}</select><button class="pill" id="refresh">↻</button></div></header><main class="main">${S.error?`<p>${esc(S.error)}</p>`:''}${({home,competitions,calendar,roster,stats}[S.page]||home)()}</main></div><nav class="bottom glass">${nav}</nav></div>`}
async function refresh(){try{let d=await load(CONFIG,S.season);S.data=d;S.season=d.seasonId;S.error=d.errors.join(' · ');render()}catch(e){S.error=e.message;render()}}
document.addEventListener('click',ev=>{let el=ev.target.closest('[data-nav],[data-slide],[data-comp],[data-mode],[data-role],[data-fixture],[data-player],#refresh');if(!el)return,d=el.dataset;if(d.nav){S.page=d.nav;location.hash=S.page;render();scrollTo({top:0,behavior:'smooth'})}else if(d.slide!==undefined){S.slide=Number(d.slide);render()}else if(d.comp){S.comp=d.comp;render()}else if(d.mode){S.mode=d.mode;render()}else if(d.role){S.role=d.role;render()}else if(d.fixture){let f=S.data.fixtures.find(x=>x.id===d.fixture);if(f){$('detail-content').innerHTML=`<h2>Match Center</h2>${duel(f)}<p>${date(f.kickoff_at)} · ${time(f.kickoff_at)} · Giornata ${esc(f.round_no??'—')}</p>`;$('detail').showModal()}}else if(d.player){let p=S.data.stats.find(x=>x.player_id===d.player);if(p){$('detail-content').innerHTML=`<h2>${esc(p.first_name)} ${esc(p.last_name)}</h2><p>Presenze ${esc(p.appearances??'—')} · Gol ${esc(p.goals??'—')} · Assist ${esc(p.assists??'—')} · Rating ${esc(p.avg_rating??'—')}</p>`;$('detail').showModal()}}else refresh()});
document.addEventListener('change',e=>{if(e.target.id==='season'){S.season=e.target.value;refresh()}});document.addEventListener('input',e=>{if(e.target.id==='search'){S.search=e.target.value;$('players').innerHTML=playerGrid()}});
S.page=tabs.find(x=>x[0]===location.hash.slice(1))?.[0]||'home';refresh();setInterval(()=>{let n=slides().length;if(n>1&&!document.hidden&&!matchMedia('(prefers-reduced-motion:reduce)').matches){S.slide=(S.slide+1)%n;if(S.page==='home')render()}},CONFIG.carouselDelayMs);