import {CONFIG} from '../src/config.js';
import {load} from './data.js';

const $=q=>document.querySelector(q);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v||'').toLowerCase().replace(/[^a-z0-9]/g,'');
const state={page:'home',season:null,competition:null,matchIndex:0,calendar:'all',role:'all',search:'',data:null,error:''};
const pages=[['home','Home','⌂'],['competitions','Competizioni','◈'],['calendar','Calendario','▦'],['roster','Rosa','♙'],['stats','Statistiche','⌁']];

function teamName(){return state.data?.team?.name||CONFIG.fallbackTeamName}
function ours(n){return norm(n)===norm(teamName())}
function finished(f){return ['finished','completed','finalized'].includes(f.status)}
function dt(v,opt){return v?new Intl.DateTimeFormat('it-IT',opt).format(new Date(v)):'—'}
const day=v=>dt(v,{day:'2-digit',month:'short'}), clock=v=>dt(v,{hour:'2-digit',minute:'2-digit'});
function games(){return (state.data?.fixtures||[]).filter(f=>ours(f.home_team)||ours(f.away_team)).sort((a,b)=>new Date(a.kickoff_at)-new Date(b.kickoff_at))}
function future(){return games().filter(f=>!finished(f)&&new Date(f.kickoff_at)>Date.now()-7200000)}
function past(){return games().filter(finished).reverse()}
function score(f){return f.home_score!=null&&f.away_score!=null?f.home_score+' – '+f.away_score:'–'}
function logo(name,small=false){let x=ours(name)?state.data.team:(state.data.opponents||[]).find(o=>norm(o.name)===norm(name)||norm(o.short_name)===norm(name));return `<span class="crest ${small?'crest-sm':''}">${x?.logo_url?`<img src="${esc(x.logo_url)}" alt="">`:`<b>${esc(String(name).slice(0,2).toUpperCase())}</b>`}</span>`}
function nav(){return pages.map(([id,label,icon])=>`<button class="nav-item ${state.page===id?'active':''}" data-page="${id}"><i>${icon}</i><span>${label}</span></button>`).join('')}
function heading(kicker,title,desc=''){return `<section class="page-heading"><div><small>${kicker}</small><h1>${title}</h1>${desc?`<p>${desc}</p>`:''}</div></section>`}
function filters(items,key,current){return `<div class="filters">${items.map(([id,label])=>`<button class="${id===current?'on':''}" data-${key}="${esc(id)}">${esc(label)}</button>`).join('')}</div>`}
function matchCard(f){return `<button class="match-line" data-match="${f.id}"><span class="date-tile"><b>${day(f.kickoff_at).split(' ')[0]}</b><small>${day(f.kickoff_at).split(' ')[1]||''}</small></span><span class="match-names"><b>${esc(f.home_team)} · ${esc(f.away_team)}</b><small>${esc(clock(f.kickoff_at))} · Giornata ${esc(f.round_no??'—')}</small></span><span class="line-score">${score(f)}</span></button>`}
function standings(comp,limit=99){let a=(state.data.standings||[]).filter(x=>!comp||x.competition_id===comp).sort((a,b)=>b.points-a.points||b.goal_difference-a.goal_difference||b.goals_for-a.goals_for).slice(0,limit);if(!a.length)return '<div class="empty">Classifica non disponibile</div>';return `<div class="table-wrap"><table><thead><tr><th>#</th><th>Squadra</th><th>G</th><th>V</th><th>N</th><th>P</th><th>DR</th><th>Pt</th></tr></thead><tbody>${a.map((x,i)=>`<tr class="${ours(x.team)?'mine':''}"><td>${i+1}</td><td><span class="team-cell">${logo(x.team,true)}<b>${esc(x.team)}</b></span></td><td>${x.played}</td><td>${x.won??'—'}</td><td>${x.drawn??'—'}</td><td>${x.lost??'—'}</td><td>${x.goal_difference}</td><td><b>${x.points}</b></td></tr>`).join('')}</tbody></table></div>`}
function kpi(){let k={p:0,w:0,d:0,l:0,gf:0,ga:0};for(let f of past()){let gf=ours(f.home_team)?f.home_score:f.away_score,ga=ours(f.home_team)?f.away_score:f.home_score;if(gf==null||ga==null)continue;k.p++;k.gf+=gf;k.ga+=ga;k[gf>ga?'w':gf<ga?'l':'d']++}return `<div class="kpis">${[['p','Partite'],['w','Vittorie'],['d','Pareggi'],['l','Sconfitte'],['gf','Gol fatti'],['ga','Gol subiti']].map(([x,l])=>`<div class="kpi glass"><b>${k[x]}</b><small>${l}</small></div>`).join('')}</div>`}
function hero(){let list=[...future().slice(0,2),...past().slice(0,2)];if(!list.length)return '<div class="hero glass"><div class="empty">Nessuna partita</div></div>';state.matchIndex%=list.length;let f=list[state.matchIndex],live=!finished(f)&&new Date(f.kickoff_at)<Date.now();return `<section class="hero"><div class="hero-bar"><span><i class="${live?'live-dot':''}"></i>${finished(f)?'ULTIMA PARTITA':live?'LIVE':'PROSSIMA PARTITA'}</span><span>${esc(state.data.competitions.find(c=>c.id===f.competition_id)?.name||'Partita')} · G${esc(f.round_no??'—')}</span></div><div class="duel"><div class="duel-team">${logo(f.home_team)}<strong>${esc(f.home_team)}</strong></div><div class="duel-score"><small>${day(f.kickoff_at)} · ${clock(f.kickoff_at)}</small><b>${score(f)}</b><span>${finished(f)?'FINALE':live?'IN CORSO':'VS'}</span></div><div class="duel-team">${logo(f.away_team)}<strong>${esc(f.away_team)}</strong></div></div><div class="hero-bottom"><div class="dots">${list.map((_,i)=>`<button class="${i===state.matchIndex?'on':''}" data-slide="${i}"></button>`).join('')}</div><button class="primary" data-match="${f.id}">Dettaglio partita ↗</button></div></section>`}
function home(){let next=future(),last=past()[0],comp=state.data.competitions[0]?.id;return heading('MATCHDAY',teamName(),'Stagione '+(state.data.seasons.find(x=>x.id===state.season)?.name||''))+`<div class="home-top">${hero()}<aside class="glass quick"><div class="quick-head"><h2>Match feed</h2><span>live</span></div>${[...next.slice(0,2),...past().slice(0,2)].map(f=>`<button class="feed-row" data-match="${f.id}"><small>${day(f.kickoff_at)}</small><span>${logo(f.home_team,true)}<b>${esc(f.home_team)}</b></span><strong>${score(f)}</strong><span><b>${esc(f.away_team)}</b>${logo(f.away_team,true)}</span></button>`).join('')||'<div class="empty">Nessuna gara</div>'}</aside></div>`+kpi()+`<div class="dashboard-grid"><section class="glass panel"><div class="panel-head"><h2>Prossime partite</h2><button data-page="calendar">Calendario</button></div>${next.slice(0,4).map(matchCard).join('')||'<div class="empty">Nessuna gara futura</div>'}</section><section class="glass panel"><div class="panel-head"><h2>Classifica</h2><button data-page="competitions">Completa</button></div>${standings(comp,6)}</section></div>`}
function competitions(){state.competition=state.competition||state.data.competitions[0]?.id;return heading('COMPETIZIONI','Classifica e partite','Consultazione della stagione attiva.')+filters(state.data.competitions.map(c=>[c.id,c.name]),'competition',state.competition)+`<div class="dashboard-grid"><section class="glass panel"><h2>Classifica</h2>${standings(state.competition)}</section><section class="glass panel"><h2>Calendario</h2>${state.data.fixtures.filter(f=>f.competition_id===state.competition).sort((a,b)=>new Date(a.kickoff_at)-new Date(b.kickoff_at)).map(matchCard).join('')}</section></div>`}
function calendar(){let a=games().filter(f=>state.calendar==='all'||(state.calendar==='future'?!finished(f):finished(f)));return heading('CALENDARIO','Le partite del Caselle','Tutte le competizioni in ordine cronologico.')+filters([['all','Tutte'],['future','Da giocare'],['results','Risultati']],'calendar',state.calendar)+`<section class="glass panel wide">${a.map(matchCard).join('')||'<div class="empty">Nessuna partita</div>'}</section>`}
function playerGrid(){return (state.data.roster||[]).filter(r=>r.active!==false).map(r=>({r,p:state.data.stats.find(p=>p.player_id===r.player_id)})).filter(({p})=>p&&(state.role==='all'||String(p.position_group||'').toUpperCase().startsWith(state.role))&&(p.first_name+' '+p.last_name).toLowerCase().includes(state.search.toLowerCase())).map(({r,p})=>`<button class="player glass" data-player="${p.player_id}"><div class="player-top"><span class="avatar">${esc(p.first_name?.[0])}${esc(p.last_name?.[0])}</span><b>#${esc(r.shirt_number??'—')}</b></div><h3>${esc(p.first_name)} ${esc(p.last_name)}</h3><small>${esc(p.position_group||'Ruolo')}</small><div><span>${p.appearances??'—'} pres.</span><span>${p.goals??'—'} gol</span><span>${p.avg_rating??'—'} rat.</span></div></button>`).join('')||'<div class="empty">Nessun giocatore</div>'}
function roster(){return heading('ROSA','La squadra','Giocatori e numeri della stagione.')+filters([['all','Tutti'],['P','Portieri'],['D','Difensori'],['C','Centrocampisti'],['A','Attaccanti']],'role',state.role)+`<input id="player-search" class="search" value="${esc(state.search)}" placeholder="Cerca giocatore…"><div class="player-grid" id="player-grid">${playerGrid()}</div>`}
function stats(){let top=state.data.stats.slice().sort((a,b)=>(b.goals||0)-(a.goals||0));return heading('STATISTICHE','I numeri','Solo dati effettivamente registrati.')+kpi()+`<div class="dashboard-grid"><section class="glass panel"><h2>Marcatori</h2>${top.map((p,i)=>`<button class="rank-row" data-player="${p.player_id}"><b>${i+1}</b><span>${esc(p.first_name)} ${esc(p.last_name)}</span><strong>${p.goals??'—'} gol</strong></button>`).join('')}</section><section class="glass panel"><h2>Ultimi risultati</h2>${past().slice(0,8).map(matchCard).join('')}</section></div>`}
function render(){if(!state.data)return;let t=state.data.team,s=state.data.seasons.find(x=>x.id===state.season);$('#root').innerHTML=`<div class="app"><aside class="sidebar glass"><div class="brand">${t?.logo_url?`<img src="${esc(t.logo_url)}">`:'<b>TM</b>'}<span><b>${esc(teamName())}</b><small>Team Manager</small></span></div><nav>${nav()}</nav><div class="sidebar-foot">Stagione ${esc(s?.name||'—')}</div></aside><div class="workspace"><header class="topbar glass"><div class="mobile-brand">${t?.logo_url?`<img src="${esc(t.logo_url)}">`:''}<b>${esc(teamName())}</b></div><label class="global-search">⌕ <input placeholder="Cerca…"></label><div class="top-actions"><select id="season">${state.data.seasons.map(x=>`<option value="${x.id}" ${x.id===state.season?'selected':''}>${esc(x.name)}</option>`).join('')}</select><button id="refresh">↻</button></div></header><main>${state.error?`<div class="error">${esc(state.error)}</div>`:''}${({home,competitions,calendar,roster,stats}[state.page]||home)()}</main></div><nav class="mobile-nav glass">${nav()}</nav></div>`}
async function refresh(){try{state.data=await load(CONFIG,state.season);state.season=state.data.seasonId;state.error=state.data.errors.join(' · ');render()}catch(e){state.error=e.message;$('#root').innerHTML=`<div class="loading">${esc(e.message)}</div>`}}
document.addEventListener('click',e=>{let el=e.target.closest('[data-page],[data-slide],[data-competition],[data-calendar],[data-role],[data-match],[data-player],#refresh');if(!el)return,d=el.dataset;if(d.page){state.page=d.page;location.hash=d.page;render();scrollTo(0,0)}else if(d.slide!=null){state.matchIndex=+d.slide;render()}else if(d.competition){state.competition=d.competition;render()}else if(d.calendar){state.calendar=d.calendar;render()}else if(d.role){state.role=d.role;render()}else if(d.match){let f=state.data.fixtures.find(x=>x.id===d.match);if(f){$('#detail-content').innerHTML=`<h2>Match center</h2><div class="dialog-duel">${logo(f.home_team)}<div><b>${esc(f.home_team)}</b><strong>${score(f)}</strong><b>${esc(f.away_team)}</b><small>${day(f.kickoff_at)} · ${clock(f.kickoff_at)} · Giornata ${f.round_no??'—'}</small></div>${logo(f.away_team)}</div>`;$('#detail').showModal()}}else if(d.player){let p=state.data.stats.find(x=>x.player_id===d.player);if(p){$('#detail-content').innerHTML=`<h2>${esc(p.first_name)} ${esc(p.last_name)}</h2><p>Presenze: ${p.appearances??'—'} · Gol: ${p.goals??'—'} · Assist: ${p.assists??'—'} · Rating: ${p.avg_rating??'—'}</p>`;$('#detail').showModal()}}else refresh()});
document.addEventListener('change',e=>{if(e.target.id==='season'){state.season=e.target.value;refresh()}});
document.addEventListener('input',e=>{if(e.target.id==='player-search'){state.search=e.target.value;$('#player-grid').innerHTML=playerGrid()}});
state.page=pages.some(x=>x[0]===location.hash.slice(1))?location.hash.slice(1):'home';refresh();
setInterval(()=>{if(state.page==='home'&&state.data&&!document.hidden){let n=[...future().slice(0,2),...past().slice(0,2)].length;if(n>1){state.matchIndex=(state.matchIndex+1)%n;render()}}},CONFIG.carouselDelayMs);