import {CONFIG} from '../src/config.js';
import {load} from './data.js';
const $=id=>document.getElementById(id),s={page:'home',slide:0,season:null,comp:null,mode:'all',role:'all',search:'',data:{},error:''};
const e=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const our=x=>['calciocaselle','calciocaselle08'].includes(String(x||'').toLowerCase().replace(/[^a-z0-9]/g,''));
const finished=f=>['finished','completed','finalized'].includes(f.status),mine=f=>our(f.home_team)||our(f.away_team);
const date=d=>d?new Intl.DateTimeFormat('it-IT',{day:'2-digit',month:'short'}).format(new Date(d)):'—';
const time=d=>d?new Intl.DateTimeFormat('it-IT',{hour:'2-digit',minute:'2-digit'}).format(new Date(d)):'—';
const score=f=>f.home_score!=null&&f.away_score!=null?f.home_score+' – '+f.away_score:'VS';
const tabs=[['home','Home','⌂'],['competitions','Tornei','♜'],['calendar','Partite','▦'],['roster','Rosa','♧'],['stats','Numeri','▥']];
const games=()=>s.data.fixtures?.filter(mine).sort((a,b)=>new Date(a.kickoff_at)-new Date(b.kickoff_at))||[];
const upcoming=()=>games().filter(f=>!finished(f)&&new Date(f.kickoff_at)>Date.now()-7200000);
const recent=()=>games().filter(finished).reverse();
function crest(n){const o=s.data.opponents?.find(x=>x.name===n||x.short_name===n);const src=our(n)?s.data.settings?.[0]?.team_logo_url:o?.logo_url;return '<span class="crest">'+(src&&/^https?:\/\//.test(src)?'<img alt="" src="'+e(src)+'">':e(String(n).slice(0,2).toUpperCase()))+'</span>'}
function duel(f){return '<div class="versus"><div class="team">'+crest(f.home_team)+'<strong>'+e(f.home_team)+'</strong></div><div class="score">'+e(score(f))+'<small>'+e(finished(f)?'FINALE':time(f.kickoff_at))+'</small></div><div class="team">'+crest(f.away_team)+'<strong>'+e(f.away_team)+'</strong></div></div>'}
const slides=()=>[...upcoming().slice(0,2),...recent().slice(0,2)];
function hero(){let ls=slides();if(!ls.length)return '<div class="hero"><div class="empty">Nessuna partita disponibile</div></div>';s.slide%=ls.length;const f=ls[s.slide];return '<div class="hero"><div class="hero-top"><span>'+e(finished(f)?'ULTIMO RISULTATO':'PROSSIMA PARTITA')+'</span><div class="arrows"><button data-slide="prev">‹</button><button data-slide="next">›</button></div></div><div class="hero-body"><span class="hero-caption">'+e(date(f.kickoff_at))+' · '+e(s.data.competitions?.find(c=>c.id===f.competition_id)?.name||'Partita')+'</span>'+duel(f)+'</div><div class="hero-bottom"><div class="dots">'+ls.map((x,i)=>'<button data-slide="'+i+'" class="'+(i===s.slide?'on':'')+'"></button>').join('')+'</div><button class="cta" data-fixture="'+e(f.id)+'">Match center ↗</button></div></div>'}
const panel=(title,body)=>'<div class="panel"><div class="panel-title"><h2>'+e(title)+'</h2></div>'+body+'</div>';
function row(f){return '<div class="match-row" role="button" tabindex="0" data-fixture="'+e(f.id)+'"><div class="datebox"><strong>'+e(date(f.kickoff_at).split(' ')[0])+'</strong><small>'+e(date(f.kickoff_at).split(' ')[1])+'</small></div><div class="match-text"><strong>'+e(f.home_team)+' – '+e(f.away_team)+'</strong><small>'+e(time(f.kickoff_at))+'</small></div><span class="result">'+e(score(f))+'</span></div>'}
function table(c){let rows=(s.data.standings||[]).filter(x=>!c||x.competition_id===c).sort((a,b)=>b.points-a.points||b.goal_difference-a.goal_difference);return rows.length?'<div class="table-scroll"><table><thead><tr><th>#</th><th>Squadra</th><th>G</th><th>DR</th><th>Pt</th></tr></thead><tbody>'+rows.map((x,i)=>'<tr class="'+(our(x.team)?'mine':'')+'"><td>'+(i+1)+'</td><td>'+e(x.team)+'</td><td>'+e(x.played)+'</td><td>'+e(x.goal_difference)+'</td><td><b>'+e(x.points)+'</b></td></tr>').join('')+'</tbody></table></div>':'<div class="empty">Classifica non disponibile</div>'}
function kpis(){const a={played:0,w:0,d:0,l:0,gf:0,ga:0};for(const f of recent()){if(f.home_score==null||f.away_score==null)continue;const gf=our(f.home_team)?f.home_score:f.away_score,ga=our(f.home_team)?f.away_score:f.home_score;a.played++;a.gf+=gf;a.ga+=ga;a[gf>ga?'w':gf<ga?'l':'d']++}return '<div class="stats-strip">'+[['played','Giocate'],['w','Vittorie'],['d','Pareggi'],['l','Sconfitte'],['gf','Gol fatti'],['ga','Gol subiti']].map(([k,t])=>'<div class="stat"><strong>'+a[k]+'</strong><small>'+t+'</small></div>').join('')+'</div>'}
const head=(eye,title,desc)=>'<div class="head"><div><div class="overline">'+e(eye)+'</div><h1>'+e(title)+'</h1><p class="sub">'+e(desc)+'</p></div><span class="tag">'+e(s.data.seasons?.find(x=>x.id===s.season)?.name||'Stagione')+'</span></div>';
function home(){return head('MATCHDAY','Ogni partita conta.','La stagione della tua squadra.')+'<div class="hero-grid">'+hero()+'<aside class="feed"><h2>Match feed</h2>'+[...upcoming().slice(0,2),...recent().slice(0,1)].map(f=>'<div class="feedgame" data-fixture="'+e(f.id)+'"><small>'+e(date(f.kickoff_at))+'</small><div class="feedgame-row"><b>'+e(f.home_team)+'</b><strong>'+e(score(f))+'</strong><b>'+e(f.away_team)+'</b></div></div>').join('')+'</aside></div>'+kpis()+'<div class="columns"><div class="stack">'+panel('In arrivo',upcoming().slice(0,4).map(row).join('')||'<div class="empty">Nessuna gara futura</div>')+panel('Ultimi risultati',recent().slice(0,4).map(row).join('')||'<div class="empty">Nessun risultato</div>')+'</div><div class="stack">'+panel('Classifica',table(s.data.competitions?.[0]?.id))+'</div></div>'}
function filters(arr,key,val){return '<div class="filters">'+arr.map(([id,t])=>'<button class="filter '+(id===val?'on':'')+'" data-'+key+'="'+e(id)+'">'+e(t)+'</button>').join('')+'</div>'}
function competitions(){s.comp=s.comp||s.data.competitions?.[0]?.id;return head('TORNEI','Competizioni.','Classifiche e partite registrate.')+filters((s.data.competitions||[]).map(c=>[c.id,c.name]),'comp',s.comp)+'<div class="columns"><div class="stack">'+panel('Classifica',table(s.comp))+'</div><div class="stack">'+panel('Partite',(s.data.fixtures||[]).filter(x=>x.competition_id===s.comp).map(row).join(''))+'</div></div>'}
function calendar(){let matches=games().filter(f=>s.mode==='all'||(s.mode==='results'?finished(f):!finished(f)));return head('PARTITE','Calendario.','Incontri della squadra.')+filters([['all','Tutte'],['future','Da giocare'],['results','Risultati']],'mode',s.mode)+panel('Programma',matches.map(row).join('')||'<div class="empty">Nessuna partita</div>')}
function playerGrid(){return (s.data.roster||[]).filter(x=>x.active!==false).map(x=>({r:x,p:s.data.stats?.find(y=>y.player_id===x.player_id)})).filter(x=>x.p&&(s.role==='all'||String(x.p.position_group||'').toUpperCase().startsWith(s.role))&&(x.p.first_name+' '+x.p.last_name).toLowerCase().includes(s.search.toLowerCase())).map(({r,p})=>'<button class="player" data-player="'+e(p.player_id)+'"><div class="player-top"><span class="avatar">'+e(p.first_name?.[0]||'')+e(p.last_name?.[0]||'')+'</span><span class="player-num">'+e(r.shirt_number??'—')+'</span></div><h3>'+e(p.first_name)+' '+e(p.last_name)+'</h3><p>'+e(p.position_group||'Ruolo non noto')+'</p><div class="player-foot">'+e(p.appearances??'—')+' presenze · '+e(p.goals??'—')+' gol</div></button>').join('')||'<div class="empty">Nessun giocatore</div>'}
function roster(){return head('CLUB','La rosa.','Giocatori della stagione.')+filters([['all','Tutti'],['P','Portieri'],['D','Difensori'],['C','Centrocampisti'],['A','Attaccanti']],'role',s.role)+'<input id="search" placeholder="Cerca giocatore…" value="'+e(s.search)+'" style="padding:12px;margin-bottom:18px;border:1px solid #dce8da;border-radius:12px;width:min(320px,100%)"><div class="players" id="players">'+playerGrid()+'</div>'}
function stats(){return head('ANALYTICS','I numeri.','Solo dati effettivamente registrati.')+kpis()+'<div class="columns"><div class="stack">'+panel('Marcatori',(s.data.stats||[]).slice().sort((a,b)=>(b.goals||0)-(a.goals||0)).map((p,i)=>'<div class="match-row"><b>'+(i+1)+'</b><div class="match-text">'+e(p.first_name+' '+p.last_name)+'</div><b>'+e(p.goals??'—')+' gol</b></div>').join(''))+'</div><div class="stack">'+panel('Risultati',recent().slice(0,8).map(row).join(''))+'</div></div>'}
function render(){const nav=tabs.map(([id,t,ico])=>'<button class="nav '+(s.page===id?'active':'')+'" data-nav="'+id+'"><span style="font-size:22px">'+ico+'</span><span>'+t+'</span></button>').join('');$('root').innerHTML='<div class="shell"><aside class="side"><div class="brand">TM.</div>'+nav+'<div class="spacer"></div></aside><div class="page"><header class="top"><div class="identity">'+crest('Calcio Caselle')+'<div><strong>Calcio Caselle</strong><small>Team Manager · '+e(s.data.seasons?.find(x=>x.id===s.season)?.name||'')+'</small></div></div><div class="top-tools"><select class="season" id="season">'+(s.data.seasons||[]).map(x=>'<option value="'+e(x.id)+'" '+(x.id===s.season?'selected':'')+'>'+e(x.name)+'</option>').join('')+'</select><button class="round" id="refresh">↻</button></div></header>'+(s.error?'<p style="color:#af482c;margin:12px 0">'+e(s.error)+'</p>':'')+({home,competitions,calendar,roster,stats}[s.page]||home)()+'</div><nav class="bottom">'+nav+'</nav></div>'}
async function refresh(){try{const d=await load(CONFIG,s.season);s.data=d;s.season=d.seasonId;s.error=d.errors.join(' · ');render()}catch(err){s.error=err.message;render()}}
document.addEventListener('click',ev=>{const el=ev.target.closest('[data-nav],[data-slide],[data-comp],[data-mode],[data-role],[data-fixture],[data-player],#refresh');if(!el)return;let d=el.dataset;if(d.nav){s.page=d.nav;location.hash=s.page;s.slide=0;render();scrollTo(0,0)}else if(d.slide!==undefined){let n=slides().length;if(!n)return;s.slide=d.slide==='next'?(s.slide+1)%n:d.slide==='prev'?(s.slide+n-1)%n:Number(d.slide);document.querySelector('.hero')?.replaceWith(document.createRange().createContextualFragment(hero()))}else if(d.comp){s.comp=d.comp;render()}else if(d.mode){s.mode=d.mode;render()}else if(d.role){s.role=d.role;render()}else if(d.fixture){let f=s.data.fixtures?.find(x=>x.id===d.fixture);if(f){$('detail-content').innerHTML='<h2>Match Center</h2>'+duel(f)+'<p>Data: '+e(date(f.kickoff_at))+' · '+e(time(f.kickoff_at))+'</p><p>Campo: '+e(f.venue_name||'Non registrato')+'</p>';$('detail').showModal()}}else if(d.player){let p=s.data.stats?.find(x=>x.player_id===d.player);if(p){$('detail-content').innerHTML='<h2>'+e(p.first_name+' '+p.last_name)+'</h2><p>Presenze: '+e(p.appearances??'—')+' · Gol: '+e(p.goals??'—')+' · Assist: '+e(p.assists??'—')+'</p>';$('detail').showModal()}}else if(el.id==='refresh')refresh()});
document.addEventListener('change',ev=>{if(ev.target.id==='season'){s.season=ev.target.value;refresh()}});
document.addEventListener('input',ev=>{if(ev.target.id==='search'){s.search=ev.target.value;$('players').innerHTML=playerGrid()}});
s.page=tabs.find(x=>x[0]===location.hash.slice(1))?.[0]||'home';refresh();
setInterval(()=>{let n=slides().length,el=document.querySelector('.hero');if(n>1&&el&&!document.hidden&&!el.matches(':hover')&&!matchMedia('(prefers-reduced-motion:reduce)').matches){s.slide=(s.slide+1)%n;el.replaceWith(document.createRange().createContextualFragment(hero()))}},7500);
