import {CONFIG} from './config.js';
import {normalizeName,isFinished,isLive,scoreText,matchResult,computeTeamSummary} from './domain.js';
import {loadReference,loadSeason,getMatchDetail,clearCache,signIn,signOut,sessionInfo} from './data.js';

const MENU = [
  ['home','Home','home'],['competitions','Competizioni','trophy'],['calendar','Calendario','calendar'],
  ['roster','Rosa','users'],['stats','Statistiche','chart'],['matches','Match Center','field'],['settings','Setup','settings']
];
const MOBILE = MENU.slice(0,5);
const $ = id => document.getElementById(id);
const state = {view:'home',reference:{},season:{},seasonId:null,team:null,competitionsFilter:'all',calendarFilter:'upcoming',calendarCompetition:'all',competitionId:null,fixtureOnlyOur:false,rosterRole:'all',rosterSearch:'',carouselIndex:0,carouselTimer:null,user:{session:null,role:null},matchId:null,matchTab:'general',detail:null,loading:true,error:null,seasonRequestId:0};
const icons = {
  home:'<path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1z"/>',
  trophy:'<path d="M7 4h10v5a5 5 0 0 1-10 0zM7 6H4v3a4 4 0 0 0 4 4m9-7h3v3a4 4 0 0 1-4 4m-6 2v4m-4 2h8"/>',
  calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4m10-4v4M3 10h18M7 14h3m3 0h4M7 18h3"/>',
  users:'<circle cx="9" cy="8" r="3"/><path d="M3 20v-2a6 6 0 0 1 12 0v2M17 6a3 3 0 0 1 0 6m0 2a5 5 0 0 1 4 5"/>',
  chart:'<path d="M4 20V9h4v11m4 0V4h4v16m4 0v-8h3v8M2 20h20"/>',
  field:'<rect x="3" y="4" width="18" height="16" rx="2"/><path d="M12 4v16m-9-8h5m8 0h5"/><circle cx="12" cy="12" r="3"/>',
  settings:'<circle cx="12" cy="12" r="3"/><path d="m10 2-.5 2.4-2 1-2.2-1-2 3.5 1.8 1.8v2.5l-1.8 1.8 2 3.5 2.2-1 2 1L10 21h4l.5-2.5 2-1 2.2 1 2-3.5-1.8-1.8v-2.5l1.8-1.8-2-3.5-2.2 1-2-1L14 2z"/>',
};
const svg = type => `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[type]||icons.home}</svg>`;
const h = val => String(val??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeURL = u => {try{const x=new URL(String(u));return ['https:','http:'].includes(x.protocol)?h(x.href):''}catch{return''}};
const norm = normalizeName;
const fmtDate=(s,options={day:'2-digit',month:'short'})=>s?new Intl.DateTimeFormat(CONFIG.locale,{timeZone:CONFIG.timeZone,...options}).format(new Date(s)):'—';
const fmtTime=s=>s?new Intl.DateTimeFormat(CONFIG.locale,{hour:'2-digit',minute:'2-digit',timeZone:CONFIG.timeZone}).format(new Date(s)):'—';
const matchFinished = isFinished;
const matchLive = isLive;
const matchScore = scoreText;
const activeSeason=()=>state.reference.seasons?.find(s=>s.id===state.seasonId);
const competitions=()=>state.season.competitions||[];
const fixtures=()=>state.season.fixtures||[];
const standings=()=>state.season.standings||[];
const roster=()=>state.season.roster||[];
const stats=()=>state.season.playerStats||[];
const players=()=>state.season.players||[];
const nameOf=player=>player?`${player.first_name||''} ${player.last_name||''}`.trim():'Giocatore non identificato';
const playerById=id=>players().find(x=>x.id===id)||stats().find(x=>x.player_id===id);
const teamName=()=>state.team?.name||CONFIG.fallbackTeamName;
const ours=name=>{const n=norm(name);if(!n)return false;const candidates=[teamName(),state.team?.short_name,CONFIG.fallbackTeamName,'Calcio Caselle 08'].filter(Boolean).map(norm);return candidates.includes(n)};
const mine=f=>ours(f.home_team)||ours(f.away_team);
const teamLogo=name=>ours(name)?state.team?.logo_url:state.reference.opponents?.find(x=>norm(x.name)===norm(name)||norm(x.short_name)===norm(name))?.logo_url;
const crest=(name,cls='')=>{let src=safeURL(teamLogo(name));let letters=String(name||'TM').trim().split(/\s+/).slice(0,2).map(s=>s[0]||'').join('').toUpperCase();return `<span class="crest ${cls}" aria-label="${h(name)}">${src?`<img alt="" loading="lazy" src="${src}" onerror="this.remove()">`:h(letters)}</span>`};
const panel=(title,body,more='')=>`<section class="panel"><div class="panel-head"><h2>${h(title)}</h2>${more}</div>${body}</section>`;
const empty=(title,desc='Nessun dato disponibile per la selezione corrente.')=>`<div class="empty-state"><div class="empty-graphic">◇</div><strong>${h(title)}</strong><p>${h(desc)}</p></div>`;
const badge=(text,accent=false)=>`<span class="chip ${accent?'accent':''}">${accent?'<span class="chip-dot"></span>':''}${h(text)}</span>`;
const goButton=(view,label='Apri dettagli →')=>`<button type="button" class="text-link" data-go="${h(view)}">${h(label)}</button>`;
const title=(section,headline,desc,extra='')=>`<div class="page-head"><div><div class="eyebrow">${h(section)}</div><h1>${headline}</h1><p>${h(desc)}</p></div><div class="head-right">${extra}</div></div>`;
const errorMessages=()=>[state.reference,state.season].flatMap(block=>Object.entries(block).filter(([k])=>k.endsWith('Error')).map(([k,v])=>`${k.replace('Error','')}: ${v}`));
const errorPanel=()=>state.error?`<div class="error-banner">${h(state.error)}</div>`:errorMessages().length?`<div class="error-banner">Alcune sezioni non sono accessibili: ${h(errorMessages().join(' · '))}</div>`:'';

function navInit(){
  $('desktopNav').innerHTML=MENU.map(([id,label,ico])=>`<button class="nav-button" data-nav="${id}">${svg(ico)}<span>${h(label)}</span></button>`).join('');
  $('mobileNav').innerHTML=MOBILE.map(([id,label,ico])=>`<button type="button" data-nav="${id}">${svg(ico)}<span>${h(label)}</span></button>`).join('');
}
function nav(view,{scroll=true}={}){
  if(!MENU.some(([id])=>id===view))view='home';
  state.view=view;state.carouselIndex=0;state.matchId=null;
  location.hash=view;
  render();if(scroll)window.scrollTo({top:0,behavior:'instant'});
}
function updateNav(){
  document.querySelectorAll('[data-nav]').forEach(el=>{const isActive=el.dataset.nav===state.view;el.classList.toggle('active',isActive);if(isActive)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current')});
  const label=MENU.find(([id])=>id===state.view)?.[1]||'Home';$('topbarViewName').textContent=label;
  document.querySelector('.account-label small').textContent=state.user?.session?'Connesso':'Accedi';
  document.querySelector('.account-label strong').textContent=state.user?.role==='admin'?'Amministratore':state.user?.session?'Area personale':'Area personale';
}
function fillSeasonSelect(){
  $('seasonSelect').innerHTML=(state.reference.seasons||[]).map(x=>`<option value="${h(x.id)}" ${x.id===state.seasonId?'selected':''}>${h(x.name)}</option>`).join('')||'<option>Nessuna stagione</option>';
}
function connectionStatus(msg,fail=false){$('connectionStatus').classList.toggle('error',fail);$('connectionStatus').innerHTML=`<span class="connection-dot"></span> ${h(msg)}`}
function render(){
  const active = document.activeElement;
  const focusKey = active?.dataset && Object.entries(active.dataset).find(([k])=>['calendarFilter','comp','role','toggleMine'].includes(k));
  updateNav();clearInterval(state.carouselTimer);state.carouselTimer=null;
  if(state.loading){ $('view').innerHTML = skeleton(); return; }
  const routes={home:renderHome,competitions:renderCompetitions,calendar:renderCalendar,roster:renderRoster,stats:renderStats,matches:renderMatches,settings:renderSettings};
  let markup='';try{markup=(routes[state.view]||renderHome)()}catch(e){console.error(e);markup=empty('Errore nella visualizzazione','Riprova ad aggiornare.');}
  $('view').innerHTML=errorPanel()+markup;
  if(focusKey){const target=[...$('view').querySelectorAll('[data-'+focusKey[0].replace(/[A-Z]/g,m=>'-'+m.toLowerCase())+']')].find(el=>el.dataset[focusKey[0]]===focusKey[1]);target?.focus({preventScroll:true});}
  if(state.view==='home')startCarousel();
}
function skeleton(){return `<div class="page-head loading-header"><div class="skeleton skeleton-eyebrow"></div><div class="skeleton skeleton-title"></div><div class="skeleton skeleton-sub"></div></div><div class="dash-grid" aria-busy="true" aria-label="Caricamento dati"><div class="dash-col"><div class="skeleton skeleton-hero"></div><div class="skeleton skeleton-card"></div></div><div class="dash-col"><div class="skeleton skeleton-card"></div><div class="skeleton skeleton-card"></div></div></div>`}
const gameIdentity=f=>`${h(f.home_team)} · ${h(f.away_team)}`;
const teamResult=f=>matchResult(f,ours);
function ownFixtures(){return fixtures().filter(mine)}
function recentFixtures(){return ownFixtures().filter(matchFinished).sort((a,b)=>+new Date(b.kickoff_at)-+new Date(a.kickoff_at))}
function nextFixture(){return ownFixtures().filter(f=>!matchFinished(f)&&new Date(f.kickoff_at)>=new Date(Date.now()-7200000)).sort((a,b)=>+new Date(a.kickoff_at)-+new Date(b.kickoff_at))[0]}
const summary=()=>computeTeamSummary(fixtures(),ours);
function scoreboard(f){return `<div class="scoreboard"><div class="team-column">${crest(f.home_team)}<strong>${h(f.home_team)}</strong><small>Casa</small></div><div class="score-center"><strong>${h(matchScore(f))}</strong><small>${h(matchLive(f)?'LIVE':matchFinished(f)?'FINALE':fmtTime(f.kickoff_at))}</small></div><div class="team-column">${crest(f.away_team)}<strong>${h(f.away_team)}</strong><small>Trasferta</small></div></div>`}
function heroSlides(){const upcoming=nextFixture();const last=recentFixtures()[0];const slides=[];
  if(upcoming)slides.push({label:'PROSSIMA PARTITA',fixture:upcoming,cta:'Scopri la partita'});
  if(last)slides.push({label:'ULTIMO RISULTATO',fixture:last,cta:'Rivedi il match'});
  const ranks=standings().filter(x=>x.competition_id===competitions()[0]?.id).sort((a,b)=>b.points-a.points||b.goal_difference-a.goal_difference);const index=ranks.findIndex(r=>ours(r.team));
  if(index>=0)slides.push({label:'CLASSIFICA ATTUALE',ranking:{place:index+1,points:ranks[index].points,played:ranks[index].played},cta:'Apri classifica'});
  return slides;
}
function hero(){const slides=heroSlides();if(!slides.length)return `<section class="panel hero-panel"><div class="hero-inner">${empty('Nessuna partita da mostrare','Le prossime partite e i risultati appariranno qui appena disponibili.')}</div></section>`;
  state.carouselIndex%=slides.length;const s=slides[state.carouselIndex];let content='';
  if(s.fixture)content=`<div class="hero-event-label">${matchLive(s.fixture)?'<span class="live-indicator"></span>':'<span class="hero-indicator"></span>'}${h(s.label)} · ${h(competitions().find(c=>c.id===s.fixture.competition_id)?.name||'Competizione')}</div>${scoreboard(s.fixture)}<div class="hero-meta"><span>${h(fmtDate(s.fixture.kickoff_at,{weekday:'long',day:'2-digit',month:'long'}))}</span><span>Giornata ${h(s.fixture.round_no??'—')}</span></div>`;
  else content=`<div class="hero-event-label"><span class="hero-indicator"></span>${h(s.label)}</div><div style="padding-top:18px;text-align:center"><div style="font:800 74px/1 Manrope;color:var(--accent)">${s.ranking.place}<span style="font-size:22px">ª</span></div><div class="muted" style="font-size:13px;margin-top:12px">${h(teamName())}</div><div style="margin-top:12px;font-size:12px">${s.ranking.points} punti · ${s.ranking.played} gare</div></div>`;
  return `<section class="panel hero-panel" aria-roledescription="carosello"><div class="hero-inner"><div class="hero-top"><span class="eyebrow">MATCH SPOTLIGHT</span><div class="hero-control"><button type="button" data-slide="prev" class="arrow-btn" aria-label="Precedente">‹</button><button type="button" data-slide="next" class="arrow-btn" aria-label="Successivo">›</button></div></div><div class="hero-slide">${content}</div></div><div class="hero-footer"><div class="hero-dots">${slides.map((x,i)=>`<button data-slide="${i}" aria-label="Slide ${i+1}" ${i===state.carouselIndex?'class="current"':''}></button>`).join('')}</div><button class="text-link" ${s.fixture?`data-fixture="${h(s.fixture.id)}"`:'data-go="competitions"'}>${h(s.cta)} ↗</button></div></section>`;
}
function startCarousel(){const slides=heroSlides();if(slides.length<2||window.matchMedia('(prefers-reduced-motion:reduce)').matches)return;state.carouselTimer=setInterval(()=>{if(document.visibilityState!=='visible'||state.view!=='home')return;state.carouselIndex=(state.carouselIndex+1)%slides.length;const el=document.querySelector('.hero-panel');if(el&&!el.matches(':hover')&&!el.contains(document.activeElement))el.outerHTML=hero()},CONFIG.carouselDelayMs)}
function kpi(n,label,foot=''){return `<div class="kpi"><small>${h(label)}</small><strong>${h(n)}</strong><div class="kpi-foot">${h(foot)}</div></div>`}
function matchSmall(f){return `<div class="match-row" role="button" tabindex="0" data-fixture="${h(f.id)}"><div class="match-date"><strong>${h(fmtDate(f.kickoff_at,{day:'2-digit'}))}</strong><small>${h(fmtDate(f.kickoff_at,{month:'short'}))}</small></div><div class="match-row-body"><strong>${gameIdentity(f)}</strong><small>${h(competitions().find(c=>c.id===f.competition_id)?.name||'Partita')} · ${h(fmtTime(f.kickoff_at))}</small></div><span class="match-score ${f.home_score==null?'scheduled':''}">${h(matchScore(f))}</span></div>`}
function homeForm(){const games=recentFixtures().slice(0,5).reverse();return games.length?`<div class="form-dots">${games.map(x=>`<span class="form-dot ${h(teamResult(x)||'')}">${({w:'V',d:'N',l:'P'})[teamResult(x)]||'—'}</span>`).join('')}</div><div class="tiny muted">Forma nelle ultime ${games.length} gare concluse</div>`:empty('Forma non disponibile','Nessuna partita conclusa con punteggio ufficiale.');}
function miniStandings(){const comp=competitions()[0];const rows=standings().filter(x=>x.competition_id===comp?.id).sort((a,b)=>b.points-a.points||b.goal_difference-a.goal_difference||b.goals_for-a.goals_for);if(!rows.length)return empty('Classifica non disponibile');return `<div class="table-scroll"><table class="standings-table"><thead><tr><th>#</th><th>Squadra</th><th>PG</th><th>DR</th><th>PT</th></tr></thead><tbody>${rows.slice(0,10).map((r,i)=>`<tr class="${ours(r.team)?'our-team':''}"><td class="position">${i+1}</td><td class="name-cell"><div class="row-team">${crest(r.team,'sm')} ${h(r.team)}</div></td><td>${h(r.played)}</td><td>${h(r.goal_difference)}</td><td><b>${h(r.points)}</b></td></tr>`).join('')}</tbody></table></div><p class="tiny muted">Ordine indicativo per punti e differenza reti; i criteri ufficiali possono differire.</p>`}
function renderHome(){const s=summary();const upcoming=ownFixtures().filter(f=>!matchFinished(f)&&new Date(f.kickoff_at)>=new Date(Date.now()-7200000)).sort((a,b)=>+new Date(a.kickoff_at)-+new Date(b.kickoff_at)).slice(0,3);const loggedPlayerStats=stats().find(x=>x.player_id===state.user.playerId);
return title('CLUB DASHBOARD',`La tua <span class="highlight">squadra.</span>`,`${teamName()} · Stagione ${activeSeason()?.name||'da impostare'}`,badge('DATI LIVE',true))+
`<div class="dash-grid"><div class="dash-col">${hero()}${panel('Panoramica stagionale',`<div class="kpi-grid">${kpi(s.played,'Partite giocate',`${s.w}V · ${s.d}N · ${s.l}P`)}${kpi(s.w,'Vittorie','Partite concluse')}${kpi(`${s.gf}:${s.ga}`,'Gol fatti / subiti','Risultati ufficiali')}${kpi(s.played?(s.w/s.played*100).toFixed(0)+'%':'—','Percentuale vittorie',s.played?'Calcolo sulle gare giocate':'Nessuna gara')}</div><div class="panel-head" style="margin:24px 0 6px"><h2>Forma recente</h2></div>${homeForm()}`,goButton('stats'))}${panel('Risultati recenti',recentFixtures().length?recentFixtures().slice(0,4).map(matchSmall).join(''):empty('Non ci sono risultati'),goButton('calendar'))}</div><div class="dash-col">${panel('Prossime partite',upcoming.length?upcoming.map(matchSmall).join(''):empty('Nessun incontro in programma'),goButton('calendar'))}${panel('Classifica · '+(competitions()[0]?.name||'Campionato'),miniStandings(),goButton('competitions'))}${state.user.session?panel('Il mio profilo',loggedPlayerStats?`<div class="kpi-grid" style="grid-template-columns:repeat(3,1fr)">${kpi(loggedPlayerStats.appearances,'Presenze')}${kpi(loggedPlayerStats.goals,'Gol')}${kpi(loggedPlayerStats.avg_rating??'—','Media voto')}</div>`:empty('Nessun giocatore associato','Il profilo attuale non ha una scheda giocatore associata.')):''}</div></div>`}
function compButtons(){const opts=competitions();if(!opts.length)return '';if(state.competitionId==='all'||!opts.some(c=>c.id===state.competitionId))state.competitionId=opts[0].id;return `<div class="filter-bar">${opts.map(c=>`<button class="filter-button ${state.competitionId===c.id?'selected':''}" data-comp="${h(c.id)}">${h(c.name)}</button>`).join('')}<span class="grow"></span><button class="filter-button ${state.fixtureOnlyOur?'selected':''}" data-toggle-mine="true">${state.fixtureOnlyOur?'Solo squadra':'Tutte le squadre'}</button></div>`}
function fullTable(compId){const rows=standings().filter(x=>x.competition_id===compId).sort((a,b)=>b.points-a.points||b.goal_difference-a.goal_difference||b.goals_for-a.goals_for);if(!rows.length)return empty('Classifica non disponibile');return `<div class="table-scroll"><table class="standings-table"><thead><tr><th>#</th><th>Squadra</th><th>PG</th><th>V</th><th>N</th><th>P</th><th>GF</th><th>GS</th><th>DR</th><th>PT</th></tr></thead><tbody>${rows.map((r,i)=>`<tr class="${ours(r.team)?'our-team':''}"><td class="position">${i+1}</td><td class="name-cell"><div class="row-team">${crest(r.team,'sm')}${h(r.team)}</div></td><td>${h(r.played)}</td><td>${h(r.won)}</td><td>${h(r.drawn)}</td><td>${h(r.lost)}</td><td>${h(r.goals_for)}</td><td>${h(r.goals_against)}</td><td>${h(r.goal_difference)}</td><td><b>${h(r.points)}</b></td></tr>`).join('')}</tbody></table></div><p class="tiny muted">Il database fornisce i punti; l'ordinamento visualizzato a parità è provvisorio finché non vengono applicati gli spareggi specifici della competizione.</p>`;}
function fixtureCard(f){let comp=competitions().find(x=>x.id===f.competition_id);return `<article class="fixture-card ${mine(f)?'mine':''}" data-fixture="${h(f.id)}" role="button" tabindex="0"><div class="fixture-meta"><strong>${h(fmtDate(f.kickoff_at,{day:'2-digit',month:'short',year:'numeric'}))}</strong><span>${h(comp?.name||'Competizione')} · ${h(fmtTime(f.kickoff_at))}</span></div><div class="fixture-teams"><span class="fixture-team">${h(f.home_team)}</span>${crest(f.home_team,'sm')}<span class="fixture-score ${f.home_score==null?'pending':''}">${h(matchScore(f))}</span>${crest(f.away_team,'sm')}<span class="fixture-team">${h(f.away_team)}</span></div><div class="fixture-place">${h(f.venue_name||'Campo da definire')}${mine(f)?'<br><span class="pill">Squadra</span>':''}</div></article>`;}
function groupedFixtures(items){if(!items.length)return empty('Nessuna partita trovata','Prova a modificare i filtri.');const groups=new Map();for(const f of items){const key=fmtDate(f.kickoff_at,{month:'long',year:'numeric'});if(!groups.has(key))groups.set(key,[]);groups.get(key).push(f)}return [...groups.entries()].map(([label,rows])=>`<section class="calendar-group"><div class="date-heading">${h(label)}</div>${rows.map(fixtureCard).join('')}</section>`).join('')}
function renderCompetitions(){const c=competitions();if(!c.length)return title('COMPETIZIONI','I <span class="highlight">tornei.</span>','Competizioni della stagione attiva')+empty('Nessuna competizione censita');const current=c.find(x=>x.id===state.competitionId)||c[0];const f=fixtures().filter(x=>x.competition_id===current.id&&(!state.fixtureOnlyOur||mine(x)));return title('COMPETIZIONI','Ogni <span class="highlight">giornata.</span>','Classifiche, calendario e risultati delle competizioni',badge(activeSeason()?.name||'Stagione'))+compButtons()+`<div class="grid grid-2"><div>${panel('Classifica ufficiale · '+current.name,fullTable(current.id))}</div><div>${panel('Calendario · '+f.length+' incontri',groupedFixtures(f.slice().sort((a,b)=>+new Date(a.kickoff_at)-+new Date(b.kickoff_at))))}</div></div>`}
function renderCalendar(){const now=Date.now();let f=ownFixtures().filter(x=>state.calendarCompetition==='all'||x.competition_id===state.calendarCompetition);if(state.calendarFilter==='upcoming')f=f.filter(x=>!matchFinished(x));else if(state.calendarFilter==='results')f=f.filter(matchFinished);f=f.slice().sort((a,b)=>state.calendarFilter==='results'?new Date(b.kickoff_at)-new Date(a.kickoff_at):new Date(a.kickoff_at)-new Date(b.kickoff_at));
return title('MATCH SCHEDULE','Il <span class="highlight">calendario.</span>','Tutti gli incontri della squadra, per stagione e competizione',badge(`${f.length} partite`))+`<section class="panel"><div class="filter-bar">${[['upcoming','Da giocare'],['results','Risultati'],['all','Tutte']].map(([id,txt])=>`<button class="filter-button ${state.calendarFilter===id?'selected':''}" data-calendar-filter="${id}">${txt}</button>`).join('')}<span class="grow"></span><select class="filter-select" data-calendar-comp aria-label="Competizione"><option value="all">Tutte le competizioni</option>${competitions().map(x=>`<option value="${h(x.id)}" ${state.calendarCompetition===x.id?'selected':''}>${h(x.name)}</option>`).join('')}</select></div>${groupedFixtures(f)}</section>`}
function statFor(p){return stats().find(x=>x.player_id===p.id)||{}}
function filteredPlayers(){let r=roster().map(r=>({...r,player:playerById(r.player_id)})).filter(x=>x.player&&x.active!==false);r=r.filter(x=>state.rosterRole==='all'||((statFor(x.player).position_group||x.player.generic_role_manual||'').toUpperCase().startsWith(state.rosterRole)));const q=norm(state.rosterSearch);if(q)r=r.filter(x=>norm(nameOf(x.player)).includes(q));return r.sort((a,b)=>String(a.player.last_name).localeCompare(String(b.player.last_name),'it'))}
function playerCard(r){const p=r.player,st=statFor(p),role=st.position_group||p.generic_role_manual||'—',pic=safeURL(p.photo_url);return `<button class="player-card" data-player="${h(p.id)}" type="button"><div class="player-top"><div class="player-face">${pic?`<img alt="" loading="lazy" src="${pic}">`:h((p.first_name?.[0]||'')+(p.last_name?.[0]||''))}</div><span class="player-number">${r.shirt_number??'—'}</span></div><strong>${h(nameOf(p))}</strong><small>${h(role)}</small><div class="player-numbers"><span><b>${h(st.appearances??'—')}</b> pres.</span><span><b>${h(st.goals??'—')}</b> gol</span><span><b>${h(st.avg_rating??'—')}</b> voto</span></div></button>`}
function renderRoster(){return title('CLUB ROSTER','La <span class="highlight">rosa.</span>','Giocatori della stagione selezionata',badge(`${roster().filter(r=>r.active).length} attivi`))+`<section class="panel"><div class="filter-bar">${[['all','Tutti'],['P','Portieri'],['D','Difensori'],['C','Centrocampisti'],['A','Attaccanti']].map(([id,label])=>`<button class="filter-button ${state.rosterRole===id?'selected':''}" data-role="${id}">${label}</button>`).join('')}<span class="grow"></span><input type="search" class="search-input" id="rosterSearch" placeholder="Cerca giocatore…" aria-label="Cerca giocatore" value="${h(state.rosterSearch)}"></div><div id="playerGrid" class="players-grid">${filteredPlayers().map(playerCard).join('')||empty('Nessun giocatore trovato')}</div></section>`}
function renderStats(){const s=summary();const completed=s.done.filter(x=>x.home_score!=null&&x.away_score!=null).slice(0,8).reverse();const top=stats().slice().sort((a,b)=>(b.goals||0)-(a.goals||0)).slice(0,7);const chart=completed.length?`<div class="bar-chart">${completed.map((x,i)=>{const gf=ours(x.home_team)?x.home_score:x.away_score;return `<div class="bar-col"><strong>${gf}</strong><div class="bar-track"><span style="height:${Math.max(3,Math.round(gf/Math.max(...completed.map(y=>Math.max(y.home_score||0,y.away_score||0)),1)*100))}%"></span></div><span>${h(fmtDate(x.kickoff_at,{day:'2-digit',month:'2-digit'}))}</span></div>`}).join('')}</div>`:empty('Nessuna serie disponibile');
return title('PERFORMANCE','I <span class="highlight">numeri.</span>','Statistiche derivate esclusivamente dalle registrazioni effettive',badge('AGGIORNATE',true))+`<div class="stat-section" style="margin-bottom:16px">${[['Partite',s.played],['Gol segnati',s.gf],['Gol subiti',s.ga],['Vittorie',s.w],['Pareggi',s.d],['Sconfitte',s.l]].map(([label,n])=>`<article class="stat-tile"><small>${h(label)}</small><strong>${h(n)}</strong></article>`).join('')}</div><div class="grid grid-2">${panel('Gol per partita · ultime 8',chart)}${panel('Marcatori',top.length?`<div class="table-scroll"><table class="roster-table"><thead><tr><th>Giocatore</th><th>Pres.</th><th>Gol</th><th>Assist</th></tr></thead><tbody>${top.map(p=>`<tr><td class="name-cell">${h(nameOf(p))}</td><td>${h(p.appearances??'—')}</td><td><b>${h(p.goals??0)}</b></td><td>${h(p.assists??0)}</td></tr>`).join('')}</tbody></table></div>`:empty('Statistiche individuali non disponibili'))}</div>`}
function renderMatches(){const list=ownFixtures().slice().sort((a,b)=>new Date(b.kickoff_at)-new Date(a.kickoff_at));return title('MATCH CENTER','Dentro la <span class="highlight">partita.</span>','Formazioni, cronologia ed eventi registrati',badge('ARCHIVIO MATCH'))+panel('Tutte le partite',list.map(matchSmall).join('')||empty('Nessuna partita disponibile'))}
function renderSettings(){const ready=['Identità squadra e stagioni','Competizioni e calendario ufficiale','Rosa e anagrafiche','Match Center consultivo','Statistiche e classifiche','Login Supabase username/password'];const later=['Gestione amministrativa di risultati e fixture','Console live con validazione eventi','Convocazioni e formazione editabile','Importazione calendario CSV/PDF','Motore di proiezione a 10.000 simulazioni','Disciplina automatica e workflow autorizzativi'];return title('AREA TECNICA','Setup <span class="highlight">club.</span>','Struttura modulare del gestionale',badge(state.user.role==='admin'?'ADMIN':'LETTURA'))+`<div class="info-banner">La prima versione è <b>consultiva</b>. Modifiche sportive e funzioni amministrative verranno abilitate per modulo dopo la verifica delle dipendenze tra fixture, match operativi e policy RLS.</div><div class="grid grid-2">${panel('Disponibile',ready.map(s=>`<p class="muted" style="font-size:12px">✓ &nbsp;${h(s)}</p>`).join(''))}${panel('Moduli pianificati',later.map(s=>`<p class="muted" style="font-size:12px">↗ &nbsp;${h(s)}</p>`).join(''))}</div>`}

function mobileMore(){modal(modalFrame('Esplora Team Manager',`<div class="field mobile-season-picker"><label for="mobileSeason">STAGIONE SPORTIVA</label><select id="mobileSeason">${(state.reference.seasons||[]).map(x=>`<option value="${h(x.id)}" ${x.id===state.seasonId?'selected':''}>${h(x.name)}</option>`).join('')}</select></div><div class="more-menu">${MENU.map(([id,label,ico])=>`<button type="button" data-menu-destination="${id}" class="more-menu-item">${svg(ico)}<span>${h(label)}</span><span aria-hidden="true">↗</span></button>`).join('')}</div>`));}
function modal(htmlContent,wide=false){const el=$('modal');el.classList.toggle('wide',wide);$('dialogContent').innerHTML=htmlContent;if(!el.open)el.showModal()}
const modalFrame=(title,body)=>`<div class="dialog-body"><div class="dialog-top"><h2>${h(title)}</h2><button type="button" data-close class="dialog-close" aria-label="Chiudi">×</button></div>${body}</div>`;
function toast(message){const el=$('toast');el.textContent=message;el.classList.add('visible');clearTimeout(toast.timeout);toast.timeout=setTimeout(()=>el.classList.remove('visible'),3200)}
async function account(){if(state.user.session){modal(modalFrame('Area personale',`<div class="info-banner">Sessione attiva · ${h(state.user.role||'Utente')}${state.user.playerId?' · Giocatore associato':''}</div><button type="button" class="primary-button" data-logout>Esci dall’account</button>`));return}modal(modalFrame('Accesso al club',`<p class="muted small" style="line-height:1.6">Usa le credenziali già registrate nel Team Manager.</p><form id="loginForm"><div class="field"><label for="loginUsername">Username</label><input id="loginUsername" autocomplete="username" autocapitalize="none" required></div><div class="field"><label for="loginPassword">Password</label><input id="loginPassword" type="password" autocomplete="current-password" required></div><p id="loginError" class="small" style="color:#ffb9a7" role="alert"></p><button class="primary-button" id="loginSubmit" type="submit">Accedi</button></form>`));}
function findOperational(f){const candidates=(state.season.matches||[]).filter(m=>m.competition_id===f.competition_id&&Math.abs(new Date(m.kickoff_at)-new Date(f.kickoff_at))<=36*3600*1000);const qualified=candidates.filter(m=>{const opp=state.reference.opponents?.find(o=>o.id===m.opponent_id);return opp&&norm(opp.name)===norm(ours(f.home_team)?f.away_team:f.home_team)&&((m.home_away==='home')===ours(f.home_team))});return qualified.length===1?qualified[0]:null}
async function showFixture(id){const fixture=fixtures().find(f=>f.id===id);if(!fixture)return;state.matchTab='general';const m=findOperational(fixture);state.matchId=m?.id||null;state.selectedFixture=fixture;state.detail=null;modal(modalFrame('Match Center',`<div class="initial-loading" style="min-height:230px"><span class="spinner"></span><p>Caricamento della partita…</p></div>`),true);if(m)state.detail=await getMatchDetail(m.id);else state.detail={participants:[],events:[]};renderFixtureDialog()}
function renderFixtureDialog(){const f=state.selectedFixture;if(!f||!$('modal').open)return;const m=state.matchId;const d=state.detail||{};const tabs=[['general','Riepilogo'],['lineup','Formazioni'],['events','Eventi']];let content='';if(state.matchTab==='general'){content=`<div class="grid grid-2">${panel('Informazioni',`<div class="muted small" style="line-height:2.2"><div>Competizione: <b>${h(competitions().find(c=>c.id===f.competition_id)?.name||'—')}</b></div><div>Data e ora: <b>${h(fmtDate(f.kickoff_at,{weekday:'long',day:'numeric',month:'long',year:'numeric'}))} · ${h(fmtTime(f.kickoff_at))}</b></div><div>Giornata: <b>${h(f.round_no??'—')}</b></div><div>Impianto: <b>${h(f.venue_name||'Non indicato')}</b></div>${f.venue_address?`<div>Indirizzo: <b>${h(f.venue_address)}</b></div>`:''}</div>`)}${panel('Registrazioni',m?`<div class="stat-section" style="grid-template-columns:repeat(2,1fr)"><div class="stat-tile"><strong>${d.participants?.length||0}</strong><small>Convocati registrati</small></div><div class="stat-tile"><strong>${d.events?.length||0}</strong><small>Eventi non rifiutati</small></div></div>`:empty('Dettaglio non collegato','La fixture è disponibile; non risulta un match operativo collegato in modo univoco.'))}</div>`}
else if(state.matchTab==='lineup'){const starters=(d.participants||[]).filter(x=>x.started||x.selection_status==='starter').sort((a,b)=>(a.tactical_slot??99)-(b.tactical_slot??99));const bench=(d.participants||[]).filter(x=>x.selection_status==='bench');content=starters.length?`<div class="grid grid-2">${panel('Undici iniziale',`<div class="lineup-field">${[starters.slice(0,1),starters.slice(1,5),starters.slice(5,8),starters.slice(8,11)].map(line=>`<div class="pitch-line">${line.map(x=>`<div class="pitch-player"><span class="shirt">${h(x.shirt_number??'•')}</span><span>${h(playerById(x.player_id)?.last_name||'—')}</span></div>`).join('')}</div>`).join('')}</div>`)}${panel('Panchina',bench.length?bench.map(x=>`<div class="timeline-item"><div class="timeline-time">${h(x.shirt_number??'—')}</div><div><strong>${h(nameOf(playerById(x.player_id)))}</strong><small>Panchina</small></div></div>`).join(''):empty('Nessuna riserva registrata'))}</div>`:empty('Formazione non disponibile','Non sono presenti undici iniziali registrati per la partita.');}
else {const events=(d.events||[]).slice().sort((a,b)=>(a.minute??999)-(b.minute??999)||(a.stoppage_minute??0)-(b.stoppage_minute??0));content=events.length?`<div class="timeline">${events.map(e=>`<div class="timeline-item"><div class="timeline-time">${e.minute==null?'s.m.':h(`${e.minute}${e.stoppage_minute?'+'+e.stoppage_minute:''}′`)}</div><div><strong>${h(({goal:'⚽ Gol',substitution:'↔ Sostituzione',yellow:'🟨 Giallo',red:'🟥 Espulsione',blue:'🔵 Blu'})[e.event_type]||e.event_type)}</strong><small>${h(nameOf(playerById(e.player_id)))}${e.secondary_player_id?' · '+h(nameOf(playerById(e.secondary_player_id))):''} · ${h(e.validation_status||'Stato da verificare')}</small></div></div>`).join('')}</div><p class="tiny muted">Gli eventi proposti non rappresentano necessariamente dati ufficializzati.</p>`:empty('Nessun evento registrato','Il risultato ufficiale può esistere anche senza marcatori o minuti registrati.');}
modal(modalFrame('Dettaglio partita',`<div class="match-detail-hero"><div class="eyebrow" style="text-align:center">${h(competitions().find(c=>c.id===f.competition_id)?.name||'Competizione')} · ${h(fmtDate(f.kickoff_at,{day:'2-digit',month:'long',year:'numeric'}))}</div>${scoreboard(f)}</div><div class="match-tabs">${tabs.map(([id,label])=>`<button class="filter-button ${state.matchTab===id?'selected':''}" data-match-tab="${id}">${label}</button>`).join('')}</div>${content}`),true)}
function playerDetail(id){const p=playerById(id);if(!p)return;const st=stats().find(x=>x.player_id===id)||{};const rr=roster().find(x=>x.player_id===id);modal(modalFrame(nameOf(p),`<div class="info-banner">${h(st.position_group||p.generic_role_manual||'Ruolo non disponibile')} · #${h(rr?.shirt_number??'—')} · ${h(activeSeason()?.name||'—')}</div><div class="stat-section">${[['Presenze',st.appearances],['Da titolare',st.starts],['Minuti',st.minutes],['Gol',st.goals],['Assist',st.assists],['Media voto',st.avg_rating],['Gialli',st.yellow_cards],['Blu',st.blue_cards],['Rossi',st.red_cards]].map(([lab,n])=>`<div class="stat-tile"><small>${lab}</small><strong>${h(n??'—')}</strong></div>`).join('')}</div><p class="tiny muted" style="margin-top:19px">Le statistiche sono relative alla stagione corrente e dipendono dai dati registrati.</p>`),true)}

async function loadAll(){connectionStatus('Connessione…');state.loading=true;try{
  state.reference=await loadReference();const list=state.reference.seasons||[];const last=state.seasonId;state.seasonId=list.some(x=>x.id===last)?last:(list.find(x=>x.status==='active')||list[0])?.id||null;
  state.team=(state.reference.teams||[]).find(t=>t.id===activeSeason()?.team_id)||state.reference.teams?.[0]||null;
  fillSeasonSelect();if(state.seasonId)await changeSeason(state.seasonId,false);else {state.error='Nessuna stagione disponibile con i permessi correnti.';state.loading=false;render();}
  connectionStatus(errorMessages().length?'Dati parziali':'Sincronizzato',!!errorMessages().length);
}catch(e){state.error=e.message;connectionStatus('Problemi di rete',true)}finally{state.loading=false;render()}}
async function changeSeason(id,showToast=true){const req=++state.seasonRequestId;state.seasonId=id;state.competitionId=null;fillSeasonSelect();state.season=await loadSeason(id);if(req!==state.seasonRequestId)return;state.error=null;state.loading=false;render();if(showToast)toast(`Stagione ${activeSeason()?.name||''} caricata`)}
async function reload(){const btn=$('refreshButton');btn.disabled=true;state.error=null;clearCache();try{await loadAll();toast('Dati aggiornati')}finally{btn.disabled=false}}
async function loadIdentity(){try{state.user=await sessionInfo()}catch(e){console.error('Sessione:',e);state.user={session:null,role:null}}}

function events(){
  document.addEventListener('click',async e=>{
    const button=e.target.closest('button,a,[data-fixture][role=button]');if(!button)return;
    if(button.dataset.menuDestination){$('modal').close();nav(button.dataset.menuDestination);return}
    if(button.dataset.nav){e.preventDefault();nav(button.dataset.nav);return}
    if(button.dataset.go){nav(button.dataset.go);return}
    if(button.dataset.slide!==undefined){const n=heroSlides().length;state.carouselIndex=button.dataset.slide==='next'?(state.carouselIndex+1)%n:button.dataset.slide==='prev'?(state.carouselIndex-1+n)%n:Math.max(0,Number(button.dataset.slide));const heroEl=document.querySelector('.hero-panel');if(heroEl){heroEl.outerHTML=hero();clearInterval(state.carouselTimer);startCarousel()}return}
    if(button.dataset.fixture){await showFixture(button.dataset.fixture);return}
    if(button.dataset.player){playerDetail(button.dataset.player);return}
    if(button.dataset.comp){state.competitionId=button.dataset.comp;render();return}
    if(button.dataset.toggleMine){state.fixtureOnlyOur=!state.fixtureOnlyOur;render();return}
    if(button.dataset.calendarFilter){state.calendarFilter=button.dataset.calendarFilter;render();return}
    if(button.dataset.role){state.rosterRole=button.dataset.role;render();return}
    if(button.dataset.close!==undefined){$('modal').close();return}
    if(button.dataset.matchTab){state.matchTab=button.dataset.matchTab;renderFixtureDialog();return}
    if(button.dataset.more!==undefined){mobileMore();return}
    if(button.dataset.logout!==undefined){await signOut();await loadIdentity();$('modal').close();await reload();toast('Sessione terminata');return}
  });
  $('accountButton').addEventListener('click',account);$('mobileAccountButton').addEventListener('click',account);
  $('refreshButton').addEventListener('click',reload);
  $('seasonSelect').addEventListener('change',e=>changeSeason(e.target.value));
  document.addEventListener('change',e=>{if(e.target.matches('[data-calendar-comp]')){state.calendarCompetition=e.target.value;render()}if(e.target.id==='mobileSeason'){$('modal').close();changeSeason(e.target.value)}});
  document.addEventListener('input',e=>{if(e.target.id==='rosterSearch'){state.rosterSearch=e.target.value;const grid=$('playerGrid');if(grid)grid.innerHTML=filteredPlayers().map(playerCard).join('')||empty('Nessun giocatore trovato')}});
  document.addEventListener('submit',async e=>{if(e.target.id!=='loginForm')return;e.preventDefault();const b=$('loginSubmit'),err=$('loginError');b.disabled=true;err.textContent='';try{await signIn($('loginUsername').value,$('loginPassword').value);clearCache();await loadIdentity();$('modal').close();await reload();toast('Accesso effettuato')}catch(ex){err.textContent=ex.message}finally{b.disabled=false}});
  document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('[data-fixture][role=button]')){e.preventDefault();showFixture(e.target.dataset.fixture)}});
  $('modal').addEventListener('click',e=>{if(e.target===$('modal'))$('modal').close()});
  const heroSwipe={x:0,y:0};
  document.addEventListener('touchstart',e=>{if(e.target.closest('.hero-panel')){heroSwipe.x=e.touches[0].clientX;heroSwipe.y=e.touches[0].clientY}},{passive:true});
  document.addEventListener('touchend',e=>{if(!heroSwipe.x||!e.target.closest('.hero-panel'))return;const dx=e.changedTouches[0].clientX-heroSwipe.x,dy=e.changedTouches[0].clientY-heroSwipe.y;heroSwipe.x=0;if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy)*1.4){const el=document.querySelector('.hero-panel');const slides=heroSlides();if(!el||!slides.length)return;state.carouselIndex=(state.carouselIndex+(dx<0?1:-1)+slides.length)%slides.length;el.outerHTML=hero();clearInterval(state.carouselTimer);startCarousel();}},{passive:true});
  document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInterval(state.carouselTimer);state.carouselTimer=null;}else if(state.view==='home'&&!state.carouselTimer)startCarousel()});
  window.addEventListener('hashchange',()=>{const path=location.hash.slice(1);if(MENU.some(([id])=>id===path)&&path!==state.view)nav(path,{scroll:false})});
}
async function boot(){
  navInit();events();
  state.view=MENU.some(([id])=>id===location.hash.slice(1))?location.hash.slice(1):'home';
  render();
  await loadIdentity();
  await loadAll();
  if('serviceWorker' in navigator && location.protocol==='https:') navigator.serviceWorker.register('./sw.js').catch(()=>{});
}
boot().catch(e=>{console.error(e);state.error='Impossibile inizializzare l’app: '+e.message;render();connectionStatus('Non connesso',true)});
